<?php

namespace Database\Seeders;

use App\Models\Branch;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class BranchSeeder extends Seeder
{
    /**
     * 38 Tunisian Bank Branches with realistic branch codes, statuses, and historical timestamps.
     * Status distribution:
     * - Active: 27 branches (~71%)
     * - Under Renovation: 7 branches (~18.4%)
     * - Inactive: 4 branches (~10.5%)
     */
    public const BRANCHES = [
        [
            'id'          => 1,
            'branch_code' => '08-300',
            'branch_name' => 'Nabeul',
            'address'     => '133 Av Habib Bourguiba - Nabeul 8000',
            'city'        => 'Nabeul',
            'phone'       => '31 372 000',
            'status'      => 'active',
            'created_at'  => '2020-02-15 08:30:00',
            'updated_at'  => '2024-01-10 14:20:00',
        ],
        [
            'id'          => 2,
            'branch_code' => '08-301',
            'branch_name' => 'Hammamet',
            'address'     => '49 Avenue de la République - Hammamet - 8050',
            'city'        => 'Hammamet',
            'phone'       => '31 372 001',
            'status'      => 'active',
            'created_at'  => '2020-06-20 09:00:00',
            'updated_at'  => '2024-03-12 11:15:00',
        ],
        [
            'id'          => 3,
            'branch_code' => '08-400',
            'branch_name' => 'Bir-Mchergua',
            'address'     => "Centre Commercial - Bir M'Cherga - 1141",
            'city'        => "Bir M'Cherga",
            'phone'       => '31 372 002',
            'status'      => 'under_renovation',
            'created_at'  => '2021-01-14 08:45:00',
            'updated_at'  => '2026-02-18 16:30:00',
        ],
        [
            'id'          => 4,
            'branch_code' => '08-109',
            'branch_name' => 'Grombalia',
            'address'     => "Av Habib BOURGUIBA RCD 'Elyes Centre' - Grombalia - 8030",
            'city'        => 'Grombalia',
            'phone'       => '31 372 003',
            'status'      => 'active',
            'created_at'  => '2021-04-10 09:15:00',
            'updated_at'  => '2024-05-22 10:00:00',
        ],
        [
            'id'          => 5,
            'branch_code' => '08-206',
            'branch_name' => 'Menzel Bouzelfa',
            'address'     => "2,4,6 Rue Taieb M'Hiri - Menzel Bouzelfa - 8010",
            'city'        => 'Menzel Bouzelfa',
            'phone'       => '31 372 004',
            'status'      => 'active',
            'created_at'  => '2021-09-01 08:30:00',
            'updated_at'  => '2024-06-15 12:45:00',
        ],
        [
            'id'          => 6,
            'branch_code' => '08-208',
            'branch_name' => 'Korba',
            'address'     => 'Av Habib Bourguiba - Korba - 8070',
            'city'        => 'Korba',
            'phone'       => '31 372 005',
            'status'      => 'active',
            'created_at'  => '2021-11-18 09:00:00',
            'updated_at'  => '2024-08-04 15:10:00',
        ],
        [
            'id'          => 7,
            'branch_code' => '08-305',
            'branch_name' => 'EL MANAR',
            'address'     => 'Av du Roi Abdelaziz Al Saoud El Manar II - Tunis - 2092',
            'city'        => 'Tunis',
            'phone'       => '31 372 006',
            'status'      => 'active',
            'created_at'  => '2020-03-01 08:00:00',
            'updated_at'  => '2025-01-12 09:30:00',
        ],
        [
            'id'          => 8,
            'branch_code' => '08-306',
            'branch_name' => 'BAB Souika',
            'address'     => '56 Place Bab Souika Tunis - Bab Souika - 1006',
            'city'        => 'Tunis',
            'phone'       => '31 372 007',
            'status'      => 'under_renovation',
            'created_at'  => '2020-05-12 08:30:00',
            'updated_at'  => '2026-03-01 14:00:00',
        ],
        [
            'id'          => 9,
            'branch_code' => '08-309',
            'branch_name' => 'UTIQUE',
            'address'     => 'Av Habib Bourguiba ZHANA - Utique - 7060',
            'city'        => 'Bizerte',
            'phone'       => '31 372 008',
            'status'      => 'active',
            'created_at'  => '2022-01-10 09:00:00',
            'updated_at'  => '2024-09-20 11:20:00',
        ],
        [
            'id'          => 10,
            'branch_code' => '08-401',
            'branch_name' => 'Agence Akouda',
            'address'     => 'AVENUE DE LA REPUBLIQUE AKOUDA 4022',
            'city'        => 'Sousse',
            'phone'       => '31 372 301',
            'status'      => 'active',
            'created_at'  => '2022-03-15 08:45:00',
            'updated_at'  => '2025-02-10 16:00:00',
        ],
        [
            'id'          => 11,
            'branch_code' => '08-102',
            'branch_name' => 'Agence Alyssa',
            'address'     => 'LE CAMPUS RUE MALAGA EL MANAR 1 2092',
            'city'        => 'Tunis',
            'phone'       => '31 372 102',
            'status'      => 'active',
            'created_at'  => '2022-05-20 08:30:00',
            'updated_at'  => '2025-03-18 10:45:00',
        ],
        [
            'id'          => 12,
            'branch_code' => '08-103',
            'branch_name' => 'Agence Avenue de Carthage',
            'address'     => '59 AVENUE DE CARTHAGE . 1000',
            'city'        => 'Tunis',
            'phone'       => '31 372 069',
            'status'      => 'active',
            'created_at'  => '2020-01-15 08:00:00',
            'updated_at'  => '2024-11-05 13:15:00',
        ],
        [
            'id'          => 13,
            'branch_code' => '08-104',
            'branch_name' => 'Agence Avenue de France',
            'address'     => '12 AVENUE DE FRANCE .',
            'city'        => 'Tunis',
            'phone'       => '31 372 060',
            'status'      => 'under_renovation',
            'created_at'  => '2020-04-10 08:30:00',
            'updated_at'  => '2026-01-25 17:00:00',
        ],
        [
            'id'          => 14,
            'branch_code' => '08-105',
            'branch_name' => 'Agence Avenue de Paris I',
            'address'     => '23 AVENUE DE PARIS .',
            'city'        => 'Tunis',
            'phone'       => '31 372 062',
            'status'      => 'active',
            'created_at'  => '2020-02-01 08:00:00',
            'updated_at'  => '2024-12-01 11:30:00',
        ],
        [
            'id'          => 15,
            'branch_code' => '08-106',
            'branch_name' => 'Agence Avenue de Paris II',
            'address'     => '25 AVENUE DE PARIS .',
            'city'        => 'Tunis',
            'phone'       => '31 372 017',
            'status'      => 'inactive',
            'created_at'  => '2020-08-15 09:00:00',
            'updated_at'  => '2025-06-30 18:00:00',
        ],
        [
            'id'          => 16,
            'branch_code' => '08-501',
            'branch_name' => 'Agence Sfax Nord',
            'address'     => 'Rue Jamel Eddine el Afghani - rdc immeuble Sibo - zone industrielle la poudriere 1 - Sfax',
            'city'        => 'Sfax',
            'phone'       => '31 372 045',
            'status'      => 'active',
            'created_at'  => '2021-03-01 08:30:00',
            'updated_at'  => '2025-04-12 14:20:00',
        ],
        [
            'id'          => 17,
            'branch_code' => '08-502',
            'branch_name' => 'Agence Sfax Medina',
            'address'     => '104 rue Mongi Slim Sfax el medina 3001',
            'city'        => 'Sfax',
            'phone'       => '31 312 046',
            'status'      => 'active',
            'created_at'  => '2020-09-10 08:00:00',
            'updated_at'  => '2025-01-15 10:10:00',
        ],
        [
            'id'          => 18,
            'branch_code' => '08-503',
            'branch_name' => 'Agence Sfax Marbourg',
            'address'     => '3 place Marbourg . 3000',
            'city'        => 'Sfax',
            'phone'       => '31 372 042',
            'status'      => 'inactive',
            'created_at'  => '2021-07-20 09:00:00',
            'updated_at'  => '2025-08-15 12:00:00',
        ],
        [
            'id'          => 19,
            'branch_code' => '08-504',
            'branch_name' => 'Agence Sfax El Jadida',
            'address'     => 'Siège régional de Sfax - avenue de la liberté (mezzanine)',
            'city'        => 'Sfax',
            'phone'       => '31 372 117',
            'status'      => 'active',
            'created_at'  => '2022-02-14 08:30:00',
            'updated_at'  => '2025-05-10 15:40:00',
        ],
        [
            'id'          => 20,
            'branch_code' => '08-505',
            'branch_name' => 'Agence Sfax Harzallah',
            'address'     => '9, rue Salem Harzallah .',
            'city'        => 'Sfax',
            'phone'       => '31 372 040',
            'status'      => 'active',
            'created_at'  => '2021-05-18 09:15:00',
            'updated_at'  => '2024-10-22 11:05:00',
        ],
        [
            'id'          => 21,
            'branch_code' => '08-506',
            'branch_name' => 'Agence Sfax Hached',
            'address'     => '148 avenue Farhat Hached .',
            'city'        => 'Sfax',
            'phone'       => '31 372 043',
            'status'      => 'active',
            'created_at'  => '2021-08-25 08:30:00',
            'updated_at'  => '2025-02-14 09:50:00',
        ],
        [
            'id'          => 22,
            'branch_code' => '08-507',
            'branch_name' => 'Agence Sfax Habib Thameur',
            'address'     => "Angle de l'Avenue Habib Thameur et de la rue Salem Harzallah",
            'city'        => 'Sfax',
            'phone'       => '31 372 034',
            'status'      => 'under_renovation',
            'created_at'  => '2020-11-05 08:30:00',
            'updated_at'  => '2026-02-01 16:15:00',
        ],
        [
            'id'          => 23,
            'branch_code' => '08-508',
            'branch_name' => 'Agence Sfax Gremda',
            'address'     => 'Route de Gremda km 1,5 .',
            'city'        => 'Sfax',
            'phone'       => '31 372 044',
            'status'      => 'active',
            'created_at'  => '2022-06-10 09:00:00',
            'updated_at'  => '2025-04-05 13:30:00',
        ],
        [
            'id'          => 24,
            'branch_code' => '08-509',
            'branch_name' => 'Agence Sfax El Habib',
            'address'     => 'Route de meharza km 3 . 3052',
            'city'        => 'Sfax',
            'phone'       => '31 372 035',
            'status'      => 'active',
            'created_at'  => '2022-09-15 08:45:00',
            'updated_at'  => '2025-06-12 10:20:00',
        ],
        [
            'id'          => 25,
            'branch_code' => '08-510',
            'branch_name' => 'Agence Sfax Center',
            'address'     => 'Avenue Hedi Chaker .',
            'city'        => 'Sfax',
            'phone'       => '31 372 031',
            'status'      => 'active',
            'created_at'  => '2021-02-20 08:00:00',
            'updated_at'  => '2025-07-08 14:15:00',
        ],
        [
            'id'          => 26,
            'branch_code' => '08-511',
            'branch_name' => 'Agence Sfax av 18 janvier 1952',
            'address'     => 'Avenue 18 janvier 1952 sfax 3000',
            'city'        => 'Sfax',
            'phone'       => '31 372 036',
            'status'      => 'active',
            'created_at'  => '2021-12-01 08:30:00',
            'updated_at'  => '2025-03-22 11:45:00',
        ],
        [
            'id'          => 27,
            'branch_code' => '08-512',
            'branch_name' => 'Agence Sfax 5 aout',
            'address'     => 'Avenue 5 aout .',
            'city'        => 'Sfax',
            'phone'       => '31 372 014',
            'status'      => 'under_renovation',
            'created_at'  => '2021-06-15 09:00:00',
            'updated_at'  => '2026-01-18 15:00:00',
        ],
        [
            'id'          => 28,
            'branch_code' => '08-513',
            'branch_name' => 'Agence Sfax 2000',
            'address'     => 'Avenue de la liberte .',
            'city'        => 'Sfax',
            'phone'       => '31 372 032',
            'status'      => 'inactive',
            'created_at'  => '2022-04-10 09:30:00',
            'updated_at'  => '2025-09-01 17:00:00',
        ],
        [
            'id'          => 29,
            'branch_code' => '08-402',
            'branch_name' => 'Agence Sayada',
            'address'     => 'Avenue Habib Bourguiba Sayada 5035',
            'city'        => 'Sayada',
            'phone'       => '31 372 259',
            'status'      => 'active',
            'created_at'  => '2023-01-20 08:45:00',
            'updated_at'  => '2025-08-10 12:30:00',
        ],
        [
            'id'          => 30,
            'branch_code' => '08-514',
            'branch_name' => 'Agence Sakiet Ezzit',
            'address'     => 'Route tunis km 6,5 av hedi chaker sakiet ezzit sfax 3021',
            'city'        => 'Sfax',
            'phone'       => '31 372 048',
            'status'      => 'active',
            'created_at'  => '2022-10-05 08:30:00',
            'updated_at'  => '2025-05-18 14:00:00',
        ],
        [
            'id'          => 31,
            'branch_code' => '08-515',
            'branch_name' => 'Agence Sakiet Eddayer',
            'address'     => 'Route de la Mahdia km 7 . 3011',
            'city'        => 'Sfax',
            'phone'       => '31 372 122',
            'status'      => 'under_renovation',
            'created_at'  => '2022-11-12 09:00:00',
            'updated_at'  => '2026-02-20 16:45:00',
        ],
        [
            'id'          => 32,
            'branch_code' => '08-403',
            'branch_name' => 'Agence Sahloul 2',
            'address'     => 'Avenue Yasser Arafet Sahloul, Sousse 4054',
            'city'        => 'Sousse',
            'phone'       => '31 372 309',
            'status'      => 'active',
            'created_at'  => '2023-03-01 08:30:00',
            'updated_at'  => '2025-09-15 11:10:00',
        ],
        [
            'id'          => 33,
            'branch_code' => '08-404',
            'branch_name' => 'Agence Sahline',
            'address'     => '26, RDC du complexe résidentiel et commercial cité El Mendra, Sahline. 5012',
            'city'        => 'Sahline',
            'phone'       => '31 372 203',
            'status'      => 'active',
            'created_at'  => '2023-05-15 09:15:00',
            'updated_at'  => '2025-10-02 15:20:00',
        ],
        [
            'id'          => 34,
            'branch_code' => '08-107',
            'branch_name' => 'Agence Mohamed V',
            'address'     => '72 AVENUE MOHAMED V . 1002',
            'city'        => 'Tunis',
            'phone'       => '31 372 108',
            'status'      => 'active',
            'created_at'  => '2020-07-01 08:00:00',
            'updated_at'  => '2025-01-20 10:00:00',
        ],
        [
            'id'          => 35,
            'branch_code' => '08-108',
            'branch_name' => 'Agence Monfleury',
            'address'     => '3 RUE ESSAHEL TUNIS 1089',
            'city'        => 'Tunis',
            'phone'       => '31 372 274',
            'status'      => 'active',
            'created_at'  => '2021-10-10 08:30:00',
            'updated_at'  => '2025-04-15 13:45:00',
        ],
        [
            'id'          => 36,
            'branch_code' => '08-110',
            'branch_name' => 'Agence Montplaisir',
            'address'     => 'RUE N 8300 BOURGEL . 1073',
            'city'        => 'Tunis',
            'phone'       => '31 372 137',
            'status'      => 'under_renovation',
            'created_at'  => '2022-07-22 08:30:00',
            'updated_at'  => '2026-02-10 17:30:00',
        ],
        [
            'id'          => 37,
            'branch_code' => '08-516',
            'branch_name' => "Agence Sfax Route de l'Aéroport",
            'address'     => "Route de l'Aéroport Km 4 - Résidence EL BARAKA - Sfax - 3064",
            'city'        => 'Sfax',
            'phone'       => '31 372 317',
            'status'      => 'active',
            'created_at'  => '2023-08-14 09:00:00',
            'updated_at'  => '2025-11-12 14:50:00',
        ],
        [
            'id'          => 38,
            'branch_code' => '08-112',
            'branch_name' => 'Point de Vente DenDen',
            'address'     => 'Rue Abou Kacem Chebbi - DenDen 2011',
            'city'        => 'Tunis',
            'phone'       => '31 312 309',
            'status'      => 'inactive',
            'created_at'  => '2024-02-01 09:30:00',
            'updated_at'  => '2025-12-05 16:00:00',
        ],
    ];

    /**
     * 38 Dedicated Branch Managers matching the 38 branches.
     * Branch 1 uses the existing persona manager (manager@bankvision.com).
     * Branches 2 through 38 have dedicated active branch managers.
     */
    public const MANAGERS = [
        1  => ['name' => 'Branch Manager',       'email' => 'manager@bankvision.com',           'phone' => '31 372 000'],
        2  => ['name' => 'Anis Trabelsi',         'email' => 'anis.trabelsi@bankvision.com',     'phone' => '31 372 001'],
        3  => ['name' => 'Salma Chaabane',        'email' => 'salma.chaabane@bankvision.com',    'phone' => '31 372 002'],
        4  => ['name' => 'Mehdi Khemir',          'email' => 'mehdi.khemir@bankvision.com',      'phone' => '31 372 003'],
        5  => ['name' => 'Nadia Bouazizi',        'email' => 'nadia.bouazizi@bankvision.com',    'phone' => '31 372 004'],
        6  => ['name' => 'Karim Gharbi',          'email' => 'karim.gharbi@bankvision.com',      'phone' => '31 372 005'],
        7  => ['name' => 'Rim Dridi',             'email' => 'rim.dridi@bankvision.com',         'phone' => '31 372 006'],
        8  => ['name' => 'Zied Jaziri',           'email' => 'zied.jaziri@bankvision.com',       'phone' => '31 372 007'],
        9  => ['name' => 'Fatma Ben Ammar',       'email' => 'fatma.benammar@bankvision.com',    'phone' => '31 372 008'],
        10 => ['name' => 'Tarek Mansour',         'email' => 'tarek.mansour@bankvision.com',     'phone' => '31 372 301'],
        11 => ['name' => 'Ines Belhadj',          'email' => 'ines.belhadj@bankvision.com',      'phone' => '31 372 102'],
        12 => ['name' => 'Hichem Zouari',         'email' => 'hichem.zouari@bankvision.com',     'phone' => '31 372 069'],
        13 => ['name' => 'Sondes Louati',         'email' => 'sondes.louati@bankvision.com',     'phone' => '31 372 060'],
        14 => ['name' => 'Walid Rekik',           'email' => 'walid.rekik@bankvision.com',       'phone' => '31 372 062'],
        15 => ['name' => 'Olfa Ghorbel',          'email' => 'olfa.ghorbel@bankvision.com',      'phone' => '31 372 017'],
        16 => ['name' => 'Mourad Fakhfakh',       'email' => 'mourad.fakhfakh@bankvision.com',   'phone' => '31 372 045'],
        17 => ['name' => 'Leila Karray',          'email' => 'leila.karray@bankvision.com',      'phone' => '31 312 046'],
        18 => ['name' => 'Sami Triki',            'email' => 'sami.triki@bankvision.com',        'phone' => '31 372 042'],
        19 => ['name' => 'Amira Sellami',         'email' => 'amira.sellami@bankvision.com',     'phone' => '31 372 117'],
        20 => ['name' => 'Nabil Hachicha',        'email' => 'nabil.hachicha@bankvision.com',    'phone' => '31 372 040'],
        21 => ['name' => 'Houda Kammoun',         'email' => 'houda.kammoun@bankvision.com',     'phone' => '31 372 043'],
        22 => ['name' => 'Wissem Masmoudi',       'email' => 'wissem.masmoudi@bankvision.com',   'phone' => '31 372 034'],
        23 => ['name' => 'Cyrine Damak',          'email' => 'cyrine.damak@bankvision.com',      'phone' => '31 372 044'],
        24 => ['name' => 'Khaled Daoud',          'email' => 'khaled.daoud@bankvision.com',      'phone' => '31 372 035'],
        25 => ['name' => 'Meriem Ben Ayed',       'email' => 'meriem.benayed@bankvision.com',    'phone' => '31 372 031'],
        26 => ['name' => 'Firas Affes',           'email' => 'firas.affes@bankvision.com',       'phone' => '31 372 036'],
        27 => ['name' => 'Nesrine Jallouli',      'email' => 'nesrine.jallouli@bankvision.com',  'phone' => '31 372 014'],
        28 => ['name' => 'Bassem Fourati',        'email' => 'bassem.fourati@bankvision.com',    'phone' => '31 372 032'],
        29 => ['name' => 'Marwa Mezghani',        'email' => 'marwa.mezghani@bankvision.com',    'phone' => '31 372 259'],
        30 => ['name' => 'Chaker Chaari',         'email' => 'chaker.chaari@bankvision.com',     'phone' => '31 372 048'],
        31 => ['name' => 'Dorsaf Baccour',        'email' => 'dorsaf.baccour@bankvision.com',    'phone' => '31 372 122'],
        32 => ['name' => 'Haythem Abid',          'email' => 'haythem.abid@bankvision.com',      'phone' => '31 372 309'],
        33 => ['name' => 'Souhir Mahjoub',        'email' => 'souhir.mahjoub@bankvision.com',    'phone' => '31 372 203'],
        34 => ['name' => 'Ramzi Cheikh',          'email' => 'ramzi.cheikh@bankvision.com',      'phone' => '31 372 108'],
        35 => ['name' => 'Manel Riahi',           'email' => 'manel.riahi@bankvision.com',       'phone' => '31 372 274'],
        36 => ['name' => 'Sofiene Ayari',         'email' => 'sofiene.ayari@bankvision.com',     'phone' => '31 372 137'],
        37 => ['name' => 'Asma Ghariani',         'email' => 'asma.ghariani@bankvision.com',     'phone' => '31 372 317'],
        38 => ['name' => 'Raouf Ben Romdhane',    'email' => 'raouf.benromdhane@bankvision.com', 'phone' => '31 312 309'],
    ];

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Seed or update all 38 branches with their data
        foreach (self::BRANCHES as $branchData) {
            Branch::updateOrCreate(
                ['id' => $branchData['id']],
                [
                    'branch_code' => $branchData['branch_code'],
                    'branch_name' => $branchData['branch_name'],
                    'address'     => $branchData['address'],
                    'city'        => $branchData['city'],
                    'phone'       => $branchData['phone'],
                    'status'      => $branchData['status'],
                    'created_at'  => $branchData['created_at'],
                    'updated_at'  => $branchData['updated_at'],
                ]
            );
        }

        // 2. Ensure each branch has a real, active branch manager user
        foreach (self::MANAGERS as $branchId => $managerData) {
            $manager = User::updateOrCreate(
                ['email' => $managerData['email']],
                [
                    'name'              => $managerData['name'],
                    'role'              => 'manager',
                    'status'            => 'active',
                    'password'          => Hash::make('password'),
                    'email_verified_at' => now(),
                    'branch_id'         => $branchId,
                    'phone'             => $managerData['phone'],
                ]
            );

            Branch::where('id', $branchId)->update(['manager_id' => $manager->id]);
        }
    }
}
