<?php

namespace Database\Seeders;

use App\Models\Branch;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Seed the branches
        $this->call(BranchSeeder::class);

        // 2. Seed the bank employees (users)
        User::factory()->create([
            'name' => 'System Administrator',
            'email' => 'admin@bankvision.com',
            'role' => 'admin',
            'status' => 'active',
        ]);

        // Create 20 random bank employees
        User::factory()->count(20)->create();

        // 3. Link Branch Managers back to the branches
        $branches = Branch::all();
        $managers = User::where('role', 'manager')->get();

        if ($managers->isEmpty()) {
            // Fallback: create a manager if none were generated by chance
            $managers = User::factory()->count(3)->create([
                'role' => 'manager',
                'status' => 'active',
            ]);
        }

        foreach ($branches as $branch) {
            $branch->update([
                'manager_id' => $managers->random()->id,
            ]);
        }

        // 4. Seed the bank customers
        $this->call(CustomerSeeder::class);

        // 5. Seed bank accounts (1–3 per customer)
        $this->call(AccountSeeder::class);

        // 6. Seed transactions (8–12 per account → 500+ records)
        $this->call(TransactionSeeder::class);

        // 7. Seed customer loans (40 records: 35 random + 5 high-risk)
        $this->call(LoanSeeder::class);

        // 8. Seed alerts (33+ records)
        $this->call(AlertSeeder::class);

        // 9. Seed audit logs (120+ entries across employees)
        $this->call(AuditLogSeeder::class);

        // 10. Seed drag & drop dashboard layouts for all users (role-tailored)
        $this->call(DashboardLayoutSeeder::class);
    }
}
